### ISSUE TITLE
Create KB endpoints returns 500 when no default LLM exists

### ISSUE THREAD

**Issue by 634750802** [pingcap/autoflow#427]
LLM
```python
2024-12-02 13:25:02 2024-12-02 05:25:02,605 - app.api.admin_routes.knowledge_base.routes:90 - ERROR - 404: default llm is not found
2024-12-02 13:25:02 Traceback (most recent call last):
2024-12-02 13:25:02   File "/app/app/api/admin_routes/knowledge_base/routes.py", line 62, in create_knowledge_base
2024-12-02 13:25:02     create.llm_id = llm_repo.must_get_default_llm(session).id
2024-12-02 13:25:02                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-02 13:25:02   File "/app/app/repositories/llm.py", line 33, in must_get_default_llm
2024-12-02 13:25:02     raise DefaultLLMNotFoundError()
2024-12-02 13:25:02 app.exceptions.DefaultLLMNotFoundError: 404: default llm is not found
2024-12-02 13:25:02 2024-12-02 05:25:02,607 - sqlalchemy.engine.Engine:2702 - INFO - ROLLBACK
2024-12-02 13:25:02 2024-12-02 05:25:02,609 - sqlalchemy.engine.Engine:2702 - INFO - ROLLBACK
2024-12-02 13:25:02 2024-12-02 05:25:02,610 - uvicorn.access:466 - INFO - 172.21.0.7:42454 - "POST /api/v1/admin/knowledge_bases HTTP/1.1" 500
```

Embedding Model
```python
2024-12-02 13:26:36 2024-12-02 05:26:36,426 - app.api.admin_routes.knowledge_base.routes:90 - ERROR - 404: default embedding model is not found
2024-12-02 13:26:36 Traceback (most recent call last):
2024-12-02 13:26:36   File "/app/app/api/admin_routes/knowledge_base/routes.py", line 65, in create_knowledge_base
2024-12-02 13:26:36     create.embedding_model_id = embed_model_repo.must_get_default_model(session).id
2024-12-02 13:26:36                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-02 13:26:36   File "/app/app/repositories/embedding_model.py", line 72, in must_get_default_model
2024-12-02 13:26:36     raise DefaultEmbeddingModelNotFoundError()
2024-12-02 13:26:36 app.exceptions.DefaultEmbeddingModelNotFoundError: 404: default embedding model is not found
2024-12-02 13:26:36 2024-12-02 05:26:36,428 - sqlalchemy.engine.Engine:2702 - INFO - ROLLBACK
2024-12-02 13:26:36 2024-12-02 05:26:36,429 - sqlalchemy.engine.Engine:2702 - INFO - ROLLBACK
2024-12-02 13:26:36 2024-12-02 05:26:36,430 - uvicorn.access:466 - INFO - 172.21.0.7:58312 - "POST /api/v1/admin/knowledge_bases HTTP/1.1" 500
```

**Comment by sykp241095** [comment]
Should we fix thus issues before releasing v0.3?

**Comment by 634750802** [comment]
Yes

**Comment by Mini256** [comment]
@634750802 For now, these error will return to the FE, please handle these errors.

```json
{
  "detail": "default embedding model is not found"
}
```

https://github.com/pingcap/autoflow/blob/5ed57cfb337fa44248772a6486196d77eb91aa8b/backend/app/api/admin_routes/knowledge_base/routes.py#L89

Also pydantic field_validator will throw some errors like this:

```json
{
  "detail": [
    {
      "type": "value_error",
      "loc": [
        "body",
        "name"
      ],
      "msg": "Value error, Please provide a name for the knowledge base",
      "input": "",
      "ctx": {
        "error": {}
      }
    }
  ]
}
```
