### ISSUE TITLE
Failed to chat without default Embedding Model

### ISSUE THREAD

**Issue by 634750802** [pingcap/autoflow#431]
```python
2024-12-02 14:51:40 2024-12-02 06:51:40,313 - app.api.routes.chat:87 - ERROR - 404: default embedding model is not found
2024-12-02 14:51:40 Traceback (most recent call last):
2024-12-02 14:51:40   File "/app/app/api/routes/chat.py", line 75, in chats
2024-12-02 14:51:40     chat_svc = ChatService(
2024-12-02 14:51:40                ^^^^^^^^^^^^
2024-12-02 14:51:40   File "/app/app/rag/chat.py", line 178, in __init__
2024-12-02 14:51:40     self._embed_model = get_default_embedding_model(db_session)
2024-12-02 14:51:40                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-02 14:51:40   File "/app/app/rag/chat_config.py", line 317, in get_default_embedding_model
2024-12-02 14:51:40     db_embed_model = embed_model_repo.must_get_default_model(session)
2024-12-02 14:51:40                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-02 14:51:40   File "/app/app/repositories/embedding_model.py", line 72, in must_get_default_model
2024-12-02 14:51:40     raise DefaultEmbeddingModelNotFoundError()
2024-12-02 14:51:40 app.exceptions.DefaultEmbeddingModelNotFoundError: 404: default embedding model is not found
```

**Comment by Mini256** [comment]
```
```
